#!/usr/bin/env bash
# modules/motd.sh — MOTD status dashboard (shown on every SSH login)

mb_module_motd() {
    mb_step "MOTD status dashboard setup"

    case "$MB_OS_FAMILY" in
        debian) _mb_motd_debian ;;
        alpine) _mb_motd_alpine ;;
        *) mb_die "MOTD setup not supported for OS: $MB_OS_FAMILY" ;;
    esac

    mb_mark_done motd
    mb_success "MOTD dashboard configured — you'll see server status on next login"
}

# ── Debian/Ubuntu (update-motd.d) ────────────────────────────────────────────

_mb_motd_debian() {
    local motd_dir="/etc/update-motd.d"
    local motd_script="${motd_dir}/99-mb-status"

    mb_backup_file "$motd_script" motd
    mkdir -p "$motd_dir"

    cat > "$motd_script" <<'MOTD_SCRIPT'
#!/usr/bin/env bash
# mb status dashboard — shown on every SSH login
# Generated by mb (mb)

printf "\n"

# System info
. /etc/os-release
KERNEL=$(uname -r)
UPTIME=$(uptime -p | sed 's/up //')
LOAD=$(cat /proc/loadavg | awk '{print $1, $2, $3}')

printf "  ┌─────────────────────────────────────────────┐\n"
printf "  │  %s %s          Kernel: %s  │\n" "$NAME" "$VERSION_ID" "$KERNEL"
printf "  │  Uptime: %-37s  │\n" "$UPTIME"
printf "  │  Load: %-39s  │\n" "$LOAD"
printf "  └─────────────────────────────────────────────┘\n"
printf "\n"

# Resource usage
CPU=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -d'.' -f1)
MEM_TOTAL=$(free -m | awk '/Mem:/ {print $2}')
MEM_USED=$(free -m | awk '/Mem:/ {print $3}')
MEM_PCT=$(awk "BEGIN {printf \"%.0f\", ($MEM_USED/$MEM_TOTAL)*100}")
DISK_USED=$(df -h / | awk 'NR==2 {print $3}')
DISK_TOTAL=$(df -h / | awk 'NR==2 {print $2}')
DISK_PCT=$(df -h / | awk 'NR==2 {print $5}')

printf "  CPU:     %s%%\n" "$CPU"
printf "  Memory:  %sM / %sM (%s%%)\n" "$MEM_USED" "$MEM_TOTAL" "$MEM_PCT"
printf "  Disk:    %s / %s (%s)\n" "$DISK_USED" "$DISK_TOTAL" "$DISK_PCT"
printf "\n"

# Docker containers
if command -v docker >/dev/null 2>&1; then
    RUNNING=$(docker ps -q 2>/dev/null | wc -l | tr -d ' ')
    STOPPED=$(docker ps -aq --filter status=exited 2>/dev/null | wc -l | tr -d ' ')
    printf "  Docker:  %s running, %s stopped\n" "$RUNNING" "$STOPPED"
fi

# CrowdSec status
if command -v cscli >/dev/null 2>&1; then
    BANNED=$(cscli decisions list -o raw 2>/dev/null | grep -v "^$" | tail -n +2 | wc -l | tr -d ' ')
    ALERTS=$(cscli alerts list -o raw 2>/dev/null | grep -v "^$" | tail -n +2 | wc -l | tr -d ' ')
    printf "  CrowdSec: %s active bans, %s alerts\n" "$BANNED" "$ALERTS"
fi

# Pending security updates
if command -v apt >/dev/null 2>&1; then
    UPDATES=$(apt list --upgradable 2>/dev/null | grep -c "security" || echo "0")
    printf "  Security updates pending: %s\n" "$UPDATES"
fi

# Recent logins
printf "\n  Recent logins:\n"
last -n 3 -w 2>/dev/null | head -3 | while read -r line; do
    printf "    %s\n" "$line"
done

printf "\n"
MOTD_SCRIPT

    chmod +x "$motd_script"

    # Disable default motd noise (on Ubuntu)
    if [ -f /etc/default/motd-news ]; then
        sed -i 's/ENABLED=1/ENABLED=0/' /etc/default/motd-news 2>/dev/null || true
    fi

    mb_detail "MOTD script installed: $motd_script"
}

# ── Alpine (/etc/motd + profile.d) ───────────────────────────────────────────

_mb_motd_alpine() {
    local profile_script="/etc/profile.d/mb-status.sh"

    cat > "$profile_script" <<'MOTD_SCRIPT'
#!/usr/bin/env bash
# mb status dashboard — shown on every login (Alpine)

printf "\n"

. /etc/os-release 2>/dev/null
KERNEL=$(uname -r)
UPTIME=$(uptime | sed 's/.*up /up /' | sed 's/,.*//')

printf "  ┌─────────────────────────────────────────────┐\n"
printf "  │  %s %s          Kernel: %s  │\n" "${NAME:-Alpine}" "${VERSION_ID:-}" "$KERNEL"
printf "  │  Uptime: %-37s  │\n" "$UPTIME"
printf "  └─────────────────────────────────────────────┘\n"
printf "\n"

MEM_TOTAL=$(free -m | awk '/Mem:/ {print $2}')
MEM_USED=$(free -m | awk '/Mem:/ {print $3}')
DISK_USED=$(df -h / | awk 'NR==2 {print $3}')
DISK_TOTAL=$(df -h / | awk 'NR==2 {print $2}')
DISK_PCT=$(df -h / | awk 'NR==2 {print $5}')

printf "  Memory:  %sM / %sM\n" "$MEM_USED" "$MEM_TOTAL"
printf "  Disk:    %s / %s (%s)\n" "$DISK_USED" "$DISK_TOTAL" "$DISK_PCT"

if command -v docker >/dev/null 2>&1; then
    RUNNING=$(docker ps -q 2>/dev/null | wc -l | tr -d ' ')
    printf "  Docker:  %s running\n" "$RUNNING"
fi

printf "\n"
MOTD_SCRIPT

    chmod +x "$profile_script"
    mb_detail "MOTD profile script installed: $profile_script"
}
